### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by liwp** [clojurewerkz/spyglass#14]
Any plans on a 1.2.0 release?

**Comment by rwilson** [comment]
bump

**Comment by michaelklishin** [comment]
Good idea. I'm on the road for a few days, will release early next week.

**Comment by rwilson** [comment]
Revisiting, any chance of a 1.2.0 release?

**Comment by michaelklishin** [comment]
[1.2.0 is up on Clojars](https://clojars.org/clojurewerkz/spyglass). Sorry that it's taken so long.
