### ISSUE TITLE
Possible to rely on Maven Central now for Spymemcached?

### ISSUE THREAD

**Issue by trentonstrong** [clojurewerkz/spyglass#18]
The readme mentions relying on the couchbase maven repo for recent releases, but 2.11.4 (and up to 2.12.0) appears to be available on Maven Central now.

Could clear up the need to add this repo downstream projects.

Reference: http://search.maven.org/#artifactdetails%7Cnet.spy%7Cspymemcached%7C2.11.4%7Cjar

**Comment by michaelklishin** [comment]
Feel free to get Spymemcached from Central and submit a PR that updates the README.
