### ISSUE TITLE
get-and-touch inconsistencies

### ISSUE THREAD

**Issue by rwilson** [clojurewerkz/spyglass#28]
The current implementation of `get-and-touch` breaks the convention of other operation fns by exposing the returned `net.spy.memcached.CASValue` directly to the caller.

**Example:**
```
user> (mc/get-and-touch c "foo" 300)
#object[net.spy.memcached.CASValue 0x4bd21f9b "{CasValue 2089/bar}"]
```

Internally, this is the same spymemcached response as `gets`, except for `gets` it's transformed to a map with keys `#{:cas :value}`.

**Example:** 
```
user> (mc/gets c "foo")
{:value "bar", :cas 2}
```

Having `get-and-touch` semantically mimic `get` and introducing a `gets-and-touch` that mimics `gets` would probably be the simplest, but that aside was there a reason for this inconsistency or would a pull request be welcome?

I was thinking of adding a convenience fn `async-get-and-touch` as well, which is missing.

**Comment by michaelklishin** [comment]
@rwilson I don't think there is a big idea behind the difference.

**Comment by michaelklishin** [comment]
Yes, a pull request would be welcome :)

**Comment by rwilson** [comment]
Resolved with merge.
